package com.behance.sdk.asynctask.listeners;

import com.behance.sdk.asynctask.params.BehanceSDKGetUserProfileTaskParams;
import com.behance.sdk.asynctasks.result.BehanceSDKGetUserProfileTaskResult;

public abstract interface IBehanceSDKGetUserProfileAsyncTaskListener
{
  public abstract void onGetUserProfileFailure(Exception paramException, BehanceSDKGetUserProfileTaskParams paramBehanceSDKGetUserProfileTaskParams);
  
  public abstract void onGetUserProfileSuccess(BehanceSDKGetUserProfileTaskResult paramBehanceSDKGetUserProfileTaskResult, BehanceSDKGetUserProfileTaskParams paramBehanceSDKGetUserProfileTaskParams);
}
